
GET http://localhost:3000/rooms

###

GET http://localhost:3000/rooms/63a1ec2fa82a85af46918da5

### 

POST http://localhost:3000/rooms
Content-Type: application/json

{
    "host": "Philip"

}

###
DELETE http://localhost:3000/subscribers/63a1bd3d471b7b00859b36ae

###
PATCH http://localhost:3000/subscribers/63a1bbc06a15ec5f5cfc793b
Content-Type: application/json

{
    "name": "New name",
    "subScribedToChannel": "Web dev"
}